/* SIGNUP ACTION TYPES */
export const UPDATE_FIRSTNAME = 'UPDATE_FIRSTNAME';
export const UPDATE_LASTNAME = 'UPDATE_LASTNAME';
export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';

/* LOGIN ACTION TYPES */
export const ENTER_USERNAME = 'ENTER_USERNAME';
export const ENTER_PASSWORD = 'ENTER_PASSWORD';

/* FORM ACTION TYPES */
export const UPDATE_TITLE = 'UPDATE_TITLE';
export const UPDATE_DESC = 'UPDATE_DESC';
export const UPDATE_TECH = 'UPDATE_TECH';
export const UPDATE_DATE = 'UPDATE_DATE';
export const GET_FORM_DATA = 'GET_FORM_DATA';
export const UPDATE_STATUS = 'UPDATE_STATUS';
export const CLEAR_FORM = 'CLEAR_FORM';
